/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsRouteImport } from './routes/news'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthletesIdRouteImport } from './routes/athletes.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesIdRoute = AthletesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AthletesRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/scores': typeof ScoresRoute
  '/trust': typeof TrustRoute
  '/api/chat': typeof ApiChatRoute
  '/athletes/$id': typeof AthletesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/scores': typeof ScoresRoute
  '/trust': typeof TrustRoute
  '/api/chat': typeof ApiChatRoute
  '/athletes/$id': typeof AthletesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/scores': typeof ScoresRoute
  '/trust': typeof TrustRoute
  '/api/chat': typeof ApiChatRoute
  '/athletes/$id': typeof AthletesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athletes'
    | '/news'
    | '/profile'
    | '/scores'
    | '/trust'
    | '/api/chat'
    | '/athletes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athletes'
    | '/news'
    | '/profile'
    | '/scores'
    | '/trust'
    | '/api/chat'
    | '/athletes/$id'
  id:
    | '__root__'
    | '/'
    | '/athletes'
    | '/news'
    | '/profile'
    | '/scores'
    | '/trust'
    | '/api/chat'
    | '/athletes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthletesRoute: typeof AthletesRouteWithChildren
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  ScoresRoute: typeof ScoresRoute
  TrustRoute: typeof TrustRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/$id': {
      id: '/athletes/$id'
      path: '/$id'
      fullPath: '/athletes/$id'
      preLoaderRoute: typeof AthletesIdRouteImport
      parentRoute: typeof AthletesRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AthletesRouteChildren {
  AthletesIdRoute: typeof AthletesIdRoute
}

const AthletesRouteChildren: AthletesRouteChildren = {
  AthletesIdRoute: AthletesIdRoute,
}

const AthletesRouteWithChildren = AthletesRoute._addFileChildren(
  AthletesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthletesRoute: AthletesRouteWithChildren,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  ScoresRoute: ScoresRoute,
  TrustRoute: TrustRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
